  source "/asylum/cg/sky_high/feature/shots/charmaster/bin/mel/skyRigTools.mel"; updateShelf("AutoMAP","/hosts/max-t2/v11/users/anupam/maya/6.0/prefs/shelves/shelf_AutoMAP.mel");

 


 //scriptNode  -beforeScript  "  source \"/asylum/cg/sky_high/feature/shots/charmaster/bin/mel/skyRigTools.mel\"; updateShelf(\"Automap\",\"/hosts/max-t2/v11/users/anupam/maya/6.0/prefs/shelves/shelf_AutoMAP.mel\");" -n 
//skyHighBakeShelfScriptNode;
// setAttr skyHighBakeShelfScriptNode.scriptType 2;
// print("\n Bakescene shelf loaded and added to current scene");

